DROP DATABASE IF EXISTS store;
CREATE DATABASE store;
USE store;

DROP TABLE IF EXISTS categories;
CREATE TABLE categories(
id INT primary key NOT NULL auto_increment,
name VARCHAR(30) unique
);

DROP TABLE IF EXISTS products;
CREATE TABLE products(
category INT REFERENCES categories(id),
description VARCHAR(255),
price FLOAT,
title VARCHAR(50),
favorite INT(1),
img_url VARCHAR(255),
id INT primary key NOT NULL auto_increment
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

insert into categories (id, name) values (1, 'Toys');
insert into categories (id, name) values (2, 'Home');
insert into categories (id, name) values (3, 'Industrial');
insert into categories (id, name) values (4, 'Tools');
insert into categories (id, name) values (5, 'Electronics');id

insert into products (category, description, price, title, favorite, img_url, id) values (1, 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 80.8, 'Pork - Side Ribs', 1, 'http://dummyimage.com/132x224.png/5fa2dd/ffffff', 1);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'ligula sit amet eleifend pede libero quis orci nullam', 79.2, 'Water - Mineral, Carbonated', 0, 'http://dummyimage.com/155x102.png/dddddd/000000', 2);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'odio donec vitae nisi nam ultrices libero non', 77.8, 'Seedlings - Clamshell', 1, 'http://dummyimage.com/131x218.png/ff4444/ffffff', 3);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', 79.4, 'Ecolab - Power Fusion', 1, 'http://dummyimage.com/236x161.png/5fa2dd/ffffff', 4);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'elementum in hac habitasse platea dictumst morbi vestibulum velit', 64.6, 'Okra', 1, 'http://dummyimage.com/191x140.png/5fa2dd/ffffff', 5);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 65.5, 'Brownies - Two Bite, Chocolate', 0, 'http://dummyimage.com/221x220.png/5fa2dd/ffffff', 6);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'nisl nunc rhoncus dui vel sem sed sagittis nam', 75.9, 'Oil - Safflower', 1, 'http://dummyimage.com/165x211.png/cc0000/ffffff', 7);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'massa quis augue luctus tincidunt nulla mollis molestie lorem', 58.7, 'Cheese - Brie', 1, 'http://dummyimage.com/189x100.png/cc0000/ffffff', 8);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'imperdiet sapien urna pretium nisl ut volutpat sapien', 75.4, 'Plasticknivesblack', 1, 'http://dummyimage.com/216x119.png/5fa2dd/ffffff', 9);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 80.1, 'Beef Dry Aged Tenderloin Aaa', 1, 'http://dummyimage.com/236x202.png/ff4444/ffffff', 10);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 77.5, 'Shrimp - Baby, Warm Water', 0, 'http://dummyimage.com/220x102.png/dddddd/000000', 11);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', 76.9, 'Salmon Steak - Cohoe 8 Oz', 0, 'http://dummyimage.com/134x179.png/ff4444/ffffff', 12);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', 78.5, 'Nut - Pecan, Halves', 1, 'http://dummyimage.com/111x155.png/ff4444/ffffff', 13);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'massa quis augue luctus tincidunt nulla mollis molestie', 65.6, 'Muffin Hinge Container 6', 0, 'http://dummyimage.com/127x149.png/cc0000/ffffff', 14);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'leo rhoncus sed vestibulum sit amet cursus id', 52.3, 'Wine - Chateau Bonnet', 1, 'http://dummyimage.com/162x103.png/dddddd/000000', 15);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'nec condimentum neque sapien placerat ante nulla justo aliquam', 96.0, 'Orange - Blood', 1, 'http://dummyimage.com/143x158.png/cc0000/ffffff', 16);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', 91.6, 'Pork - Sausage Casing', 0, 'http://dummyimage.com/232x185.png/5fa2dd/ffffff', 17);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', 63.4, 'Salt - Rock, Course', 0, 'http://dummyimage.com/209x167.png/5fa2dd/ffffff', 18);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', 80.8, 'Flavouring Vanilla Artificial', 0, 'http://dummyimage.com/194x205.png/dddddd/000000', 19);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'tellus nulla ut erat id mauris vulputate elementum nullam varius', 53.2, 'Laundry - Bag Cloth', 1, 'http://dummyimage.com/167x169.png/ff4444/ffffff', 20);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', 57.0, 'Beef - Texas Style Burger', 0, 'http://dummyimage.com/235x247.png/ff4444/ffffff', 21);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'donec posuere metus vitae ipsum aliquam non mauris morbi non', 50.4, 'Flour - Bran, Red', 1, 'http://dummyimage.com/237x200.png/5fa2dd/ffffff', 22);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'maecenas pulvinar lobortis est phasellus sit amet erat nulla', 68.3, 'Salsify, Organic', 0, 'http://dummyimage.com/191x118.png/dddddd/000000', 23);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'sit amet sem fusce consequat nulla nisl nunc nisl duis', 76.5, 'Chicken - Leg / Back Attach', 0, 'http://dummyimage.com/159x116.png/cc0000/ffffff', 24);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', 83.6, 'Grapefruit - White', 0, 'http://dummyimage.com/158x174.png/ff4444/ffffff', 25);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 98.7, 'Country Roll', 1, 'http://dummyimage.com/106x105.png/cc0000/ffffff', 26);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 76.6, 'Hot Chocolate - Individual', 1, 'http://dummyimage.com/114x175.png/5fa2dd/ffffff', 27);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 81.0, 'Longos - Lasagna Veg', 1, 'http://dummyimage.com/139x144.png/5fa2dd/ffffff', 28);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'erat curabitur gravida nisi at nibh in hac', 50.2, 'Table Cloth 62x114 White', 0, 'http://dummyimage.com/141x221.png/5fa2dd/ffffff', 29);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'luctus et ultrices posuere cubilia curae duis faucibus', 70.5, 'Flour - All Purpose', 0, 'http://dummyimage.com/125x177.png/dddddd/000000', 30);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 62.2, 'Potatoes - Yukon Gold 5 Oz', 0, 'http://dummyimage.com/201x130.png/dddddd/000000', 31);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'integer ac neque duis bibendum morbi non quam nec dui luctus', 68.9, 'Pasta - Detalini, White, Fresh', 1, 'http://dummyimage.com/171x148.png/cc0000/ffffff', 32);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'id nulla ultrices aliquet maecenas leo odio condimentum id', 73.3, 'Wild Boar - Tenderloin', 1, 'http://dummyimage.com/218x130.png/ff4444/ffffff', 33);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', 87.7, 'Onions - Dried, Chopped', 1, 'http://dummyimage.com/116x138.png/cc0000/ffffff', 34);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan', 81.2, 'Soap - Hand Soap', 1, 'http://dummyimage.com/102x128.png/5fa2dd/ffffff', 35);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 80.4, 'Cheese - Comte', 0, 'http://dummyimage.com/196x242.png/5fa2dd/ffffff', 36);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', 55.5, 'Parsnip', 0, 'http://dummyimage.com/216x210.png/dddddd/000000', 37);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 66.3, 'Chinese Foods - Pepper Beef', 0, 'http://dummyimage.com/145x167.png/5fa2dd/ffffff', 38);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'donec vitae nisi nam ultrices libero non mattis pulvinar', 92.2, 'Gloves - Goldtouch Disposable', 0, 'http://dummyimage.com/216x142.png/5fa2dd/ffffff', 39);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'nulla sed accumsan felis ut at dolor quis odio consequat', 60.8, 'Plate Pie Foil', 0, 'http://dummyimage.com/122x171.png/5fa2dd/ffffff', 40);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'in congue etiam justo etiam pretium iaculis justo', 79.8, 'Chicken - Ground', 1, 'http://dummyimage.com/113x250.png/ff4444/ffffff', 41);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'eget massa tempor convallis nulla neque libero convallis eget eleifend', 77.1, 'Iced Tea - Lemon, 460 Ml', 0, 'http://dummyimage.com/182x107.png/5fa2dd/ffffff', 42);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'elementum pellentesque quisque porta volutpat erat quisque erat eros', 89.1, 'Soho Lychee Liqueur', 0, 'http://dummyimage.com/145x187.png/ff4444/ffffff', 43);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'augue aliquam erat volutpat in congue etiam justo etiam', 64.0, 'Olives - Green, Pitted', 0, 'http://dummyimage.com/158x209.png/cc0000/ffffff', 44);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'in lacus curabitur at ipsum ac tellus semper interdum mauris', 61.2, 'Trueblue - Blueberry Cranberry', 1, 'http://dummyimage.com/109x167.png/dddddd/000000', 45);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'volutpat in congue etiam justo etiam pretium iaculis justo', 68.8, 'Tandoori Curry Paste', 1, 'http://dummyimage.com/133x158.png/dddddd/000000', 46);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 97.4, 'Lemonade - Black Cherry, 591 Ml', 1, 'http://dummyimage.com/116x100.png/ff4444/ffffff', 47);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'justo in hac habitasse platea dictumst etiam faucibus', 69.8, 'Beets - Mini Golden', 1, 'http://dummyimage.com/237x115.png/dddddd/000000', 48);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'quisque erat eros viverra eget congue eget semper', 55.5, 'Pastry - Baked Scones - Mini', 1, 'http://dummyimage.com/129x239.png/ff4444/ffffff', 49);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum', 77.0, 'Gherkin - Sour', 0, 'http://dummyimage.com/157x166.png/dddddd/000000', 50);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'velit vivamus vel nulla eget eros elementum pellentesque quisque', 74.5, 'Kellogs All Bran Bars', 1, 'http://dummyimage.com/157x203.png/ff4444/ffffff', 51);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', 70.1, 'Broom And Broom Rack White', 0, 'http://dummyimage.com/233x208.png/5fa2dd/ffffff', 52);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 55.8, 'Tea - Herbal Sweet Dreams', 1, 'http://dummyimage.com/116x163.png/ff4444/ffffff', 53);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut', 75.7, 'Beef - Top Sirloin - Aaa', 0, 'http://dummyimage.com/162x246.png/ff4444/ffffff', 54);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'enim lorem ipsum dolor sit amet consectetuer adipiscing', 88.8, 'Cookies Oatmeal Raisin', 0, 'http://dummyimage.com/111x159.png/dddddd/000000', 55);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'in purus eu magna vulputate luctus cum sociis', 56.6, 'Beans - Kidney, Canned', 1, 'http://dummyimage.com/147x188.png/ff4444/ffffff', 56);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'vestibulum rutrum rutrum neque aenean auctor gravida sem', 92.3, 'Cookie Dough - Double', 0, 'http://dummyimage.com/233x172.png/5fa2dd/ffffff', 57);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'luctus et ultrices posuere cubilia curae nulla dapibus', 70.3, 'Bread - Pita, Mini', 0, 'http://dummyimage.com/125x190.png/5fa2dd/ffffff', 58);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', 55.2, 'Peach - Halves', 0, 'http://dummyimage.com/102x150.png/5fa2dd/ffffff', 59);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 87.9, 'Beans - Black Bean, Canned', 0, 'http://dummyimage.com/247x224.png/dddddd/000000', 60);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 99.7, 'Flour - Chickpea', 1, 'http://dummyimage.com/216x118.png/dddddd/000000', 61);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut', 88.1, 'Wine - Cotes Du Rhone', 0, 'http://dummyimage.com/101x207.png/ff4444/ffffff', 62);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'nulla justo aliquam quis turpis eget elit sodales scelerisque', 69.9, 'Oil - Olive', 1, 'http://dummyimage.com/163x111.png/5fa2dd/ffffff', 63);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', 99.9, 'Lentils - Green Le Puy', 1, 'http://dummyimage.com/237x159.png/cc0000/ffffff', 64);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'velit id pretium iaculis diam erat fermentum justo nec condimentum', 53.3, 'Bread - Wheat Baguette', 1, 'http://dummyimage.com/168x230.png/dddddd/000000', 65);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'volutpat in congue etiam justo etiam pretium iaculis justo in hac', 77.1, 'Sloe Gin - Mcguinness', 0, 'http://dummyimage.com/195x119.png/5fa2dd/ffffff', 66);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', 53.9, 'Fudge - Cream Fudge', 1, 'http://dummyimage.com/154x238.png/ff4444/ffffff', 67);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'mi in porttitor pede justo eu massa donec dapibus duis at velit', 72.6, 'Artichoke - Hearts, Canned', 0, 'http://dummyimage.com/137x158.png/ff4444/ffffff', 68);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'turpis a pede posuere nonummy integer non velit donec', 70.8, 'Pickerel - Fillets', 1, 'http://dummyimage.com/141x197.png/ff4444/ffffff', 69);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 87.5, 'Corn - On The Cob', 0, 'http://dummyimage.com/170x185.png/5fa2dd/ffffff', 70);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'donec vitae nisi nam ultrices libero non mattis pulvinar', 61.8, 'Beer - Upper Canada Lager', 1, 'http://dummyimage.com/131x160.png/cc0000/ffffff', 71);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'vitae quam suspendisse potenti nullam porttitor lacus at turpis', 88.0, 'Cheese - Cream Cheese', 1, 'http://dummyimage.com/137x210.png/dddddd/000000', 72);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 50.9, 'Mix - Cocktail Strawberry Daiquiri', 0, 'http://dummyimage.com/235x225.png/5fa2dd/ffffff', 73);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'tortor risus dapibus augue vel accumsan tellus nisi', 80.7, 'Seedlings - Mix, Organic', 0, 'http://dummyimage.com/248x240.png/dddddd/000000', 74);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 83.1, 'Crackers - Water', 1, 'http://dummyimage.com/125x131.png/ff4444/ffffff', 75);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 73.5, 'Wine - Clavet Saint Emilion', 1, 'http://dummyimage.com/121x111.png/cc0000/ffffff', 76);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'amet consectetuer adipiscing elit proin interdum mauris non ligula', 89.8, 'Flour - Semolina', 1, 'http://dummyimage.com/211x115.png/5fa2dd/ffffff', 77);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', 91.3, 'Salmon - Atlantic, Fresh, Whole', 1, 'http://dummyimage.com/221x199.png/5fa2dd/ffffff', 78);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 98.4, 'Jolt Cola', 0, 'http://dummyimage.com/206x100.png/cc0000/ffffff', 79);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 51.2, 'Dragon Fruit', 1, 'http://dummyimage.com/240x174.png/cc0000/ffffff', 80);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 90.2, 'Fudge - Chocolate Fudge', 0, 'http://dummyimage.com/226x119.png/dddddd/000000', 81);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'vitae mattis nibh ligula nec sem duis aliquam convallis', 74.5, 'Salt - Celery', 0, 'http://dummyimage.com/152x168.png/5fa2dd/ffffff', 82);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'proin risus praesent lectus vestibulum quam sapien varius ut', 80.7, 'Carbonated Water - Strawberry', 1, 'http://dummyimage.com/110x211.png/dddddd/000000', 83);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 60.0, 'Lid - 0090 Clear', 0, 'http://dummyimage.com/177x150.png/5fa2dd/ffffff', 84);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', 58.6, 'Fib N9 - Prague Powder', 0, 'http://dummyimage.com/163x205.png/dddddd/000000', 85);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'pede ullamcorper augue a suscipit nulla elit ac nulla', 52.4, 'Bread - Sticks, Thin, Plain', 0, 'http://dummyimage.com/249x132.png/dddddd/000000', 86);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'cubilia curae mauris viverra diam vitae quam suspendisse', 79.2, 'Wine - Sogrape Mateus Rose', 1, 'http://dummyimage.com/231x249.png/cc0000/ffffff', 87);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'turpis donec posuere metus vitae ipsum aliquam non mauris', 63.4, 'Sherbet - Raspberry', 1, 'http://dummyimage.com/214x213.png/ff4444/ffffff', 88);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum', 98.1, 'Rum - Dark, Bacardi, Black', 0, 'http://dummyimage.com/101x102.png/dddddd/000000', 89);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 89.1, 'Crab - Dungeness, Whole', 0, 'http://dummyimage.com/101x183.png/dddddd/000000', 90);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 90.2, 'Amaretto', 1, 'http://dummyimage.com/100x193.png/ff4444/ffffff', 91);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'eu magna vulputate luctus cum sociis natoque penatibus', 76.9, 'Chocolate Bar - Oh Henry', 0, 'http://dummyimage.com/159x247.png/ff4444/ffffff', 92);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante', 83.7, 'Muffin - Mix - Mango Sour Cherry', 1, 'http://dummyimage.com/103x142.png/cc0000/ffffff', 93);
insert into products (category, description, price, title, favorite, img_url, id) values (1, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 66.0, 'Ecolab - Mikroklene 4/4 L', 0, 'http://dummyimage.com/216x248.png/5fa2dd/ffffff', 94);
insert into products (category, description, price, title, favorite, img_url, id) values (4, 'ut odio cras mi pede malesuada in imperdiet et', 51.8, 'Turnip - White, Organic', 1, 'http://dummyimage.com/237x186.png/ff4444/ffffff', 95);
insert into products (category, description, price, title, favorite, img_url, id) values (3, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus', 59.7, 'Beef - Cow Feet Split', 1, 'http://dummyimage.com/159x200.png/dddddd/000000', 96);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', 81.7, 'Bread - Rye', 0, 'http://dummyimage.com/107x119.png/5fa2dd/ffffff', 97);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'orci eget orci vehicula condimentum curabitur in libero ut massa', 69.3, 'Extract - Lemon', 1, 'http://dummyimage.com/102x168.png/dddddd/000000', 98);
insert into products (category, description, price, title, favorite, img_url, id) values (5, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 73.0, 'Nut - Macadamia', 1, 'http://dummyimage.com/171x147.png/cc0000/ffffff', 99);
insert into products (category, description, price, title, favorite, img_url, id) values (2, 'ut nunc vestibulum ante ipsum primis in faucibus orci', 57.9, 'Squid - U - 10 Thailand', 1, 'http://dummyimage.com/207x125.png/ff4444/ffffff', 100);
